#!/bin/bash

HOST=172.22.4.19
PORT=80
PROTOCOL=http

LANG=en

THREADS=1
RAMP_UP=1
DURATION=120

WAIT_TIME_SHORT=1000
WAIT_TIME_MID=3000
WAIT_TIME_LONG=5000

RESULTS_DIR=results


# JMeter JVM memory
export HEAP="-Xms2g -Xmx4g -XX:MaxMetaspaceSize=256m"

mkdir -p "$RESULTS_DIR"

TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

jmeter \
-n \
-t final_script.jmx \
-JHOST=$HOST \
-JPORT=$PORT \
-JPROTOCOL=$PROTOCOL \
-JLANG=$LANG \
-JTHREADS=$THREADS \
-JRAMP_UP=$RAMP_UP \
-JDURATION=$DURATION \
-JWAIT_TIME_SHORT=$WAIT_TIME_SHORT \
-JWAIT_TIME_MID=$WAIT_TIME_MID \
-JHINK_TIME_LONG=$WAIT_TIME_LONG \
-l "$RESULTS_DIR/results_$TIMESTAMP.jtl"